### ISSUE TITLE
Question : pourquoi les données de 'lexemple 2 ne sont pas compliant? Est-ce normal?

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/benford-calculator#1]
Si on choisit les données d'exemple N° 2 (population par pays).
http://powerful-peak-7372.herokuapp.com/checker/5232e7c099852e0200000007

Pourquoi l'application marque "It seems that the data does not comply with Benford's law. "
Alors qu'il me semble que c'est assez similaire non ?

ping @n-kb @Paulloz 

![capture decran 2013-09-13 a 16 31 32](https://f.cloud.github.com/assets/2103603/1138942/2e32262e-1c81-11e3-917a-4ef2e9452562.png)

**Comment by n-kb** [comment]
Je suis dessus présentement

**Comment by annelisebouyer** [comment]
Ok vu avec @Paulloz  c'est normal les données ne sont pas compliant malgré les apparences
