### ISSUE TITLE
Feature "store my results" : active ?

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/benford-calculator#12]
Cette feature fait quoi exactement ?

Si elle n'est pas encore implémentée il faudrait peut-etre la désactivée du front si on veut mettre l'outil en ligne today

**Comment by paulloz** [comment]
Si la checkbox est cochée, les résultats sont stockés dans la base de donnée et il y a un bouton "Share result" sur la page suivante.

**Comment by annelisebouyer** [comment]
Ok :) j'avais pas remarqué car j'arrive pas à faire fonctionne le share, mais c'est un autre ticket...
