### ISSUE TITLE
bug vue "z-statistics" sous Chrome : le chart est cassé

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/benford-calculator#2]
Par défaut après avoir uploadé mes données, j'arrive sur la vue "z-statistics" qui est ok.
Par contre si je change vers "magnitudes" puis que je retourne sur "z-statistics", le chart est cassé

(Relevé uniquement sous Chrome, c'est ok sous FF)

![capture decran 2013-09-13 a 16 33 06](https://f.cloud.github.com/assets/2103603/1138952/829cdb0a-1c81-11e3-9d80-b9608d801073.png)

**Comment by paulloz** [comment]
Sous quel OS / version de Chrome ? Je n'ai pas le soucis dans mon Chrome 27 (Linux), je vais voir un peu dans BrowserStack.

**Comment by annelisebouyer** [comment]
Ok j'ai compris comment le bug apparait, c'est vraiment bizarre j'ai jamais vu ça.

Comme mon Chrome est en français, il m'affiche le message de warning "cette page est en anglais voulez-vous la traduire". Je clique sur "Non" le bandeau de warning disparait et le chart est cassé....

**Comment by annelisebouyer** [comment]
Precision:

Meme si je ne clique pas sur "Non" et que je laisse ce bandeau, le chart est cassé.
Par contre si je choisis de ne jamais afficher ce message d'erreur tout va bien.

![capture decran 2013-09-16 a 12 41 33](https://f.cloud.github.com/assets/2103603/1148237/9c52485e-1ebc-11e3-8238-4ae885b5dfc1.png)

**Comment by paulloz** [comment]
En fait ça n'a pas de rapport direct avec le bandeau ; c'est un problème avec Highcharts quand la page se resize (pas uniquement sous Chrome).

**Comment by annelisebouyer** [comment]
Le resize ne casse plus le chart mais du coup la légende a disparu et les rollovers sont vides
C'est le même process d'apparition que lorsque le chart était cassé (resize).

![capture decran 2013-09-18 a 15 17 53](https://f.cloud.github.com/assets/2103603/1165032/c55820e4-2064-11e3-828f-100c05a87e8b.png)
![capture decran 2013-09-18 a 15 17 38](https://f.cloud.github.com/assets/2103603/1165033/c56e5ce2-2064-11e3-8a78-ca377fd9f4e9.png)

**Comment by paulloz** [comment]
Je voyais la même chose la semaine dernière mais plus aujourd'hui...
Quelqu'un peut-il confirmer / infirmer ce ticket ?

**Comment by annelisebouyer** [comment]
Oui pareil aujourd'hui il n'apparait plus. Peut-être un effet de bord positif ? :)

Je le ferme du coup, merci !
