### ISSUE TITLE
Intégration (détail) : Changer le style du bouton "Learn more"

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/benford-calculator#6]
Il ne faudrait pas que ce bouton ait le même style que les boutons d'étape 1 et 2 car du coup on a l'impression que ça fait partie des étapes.

Je le verrais bien moins grand (moins haut quoi), la typo à peine plus petite et l'icone du ? en jaune.Qu'en pensez-vous ?

**Comment by paulloz** [comment]
Quelques chose comme ça ? 
![benford](https://f.cloud.github.com/assets/437025/1165511/e423756a-206d-11e3-9bd6-f94709680525.png)

**Comment by annelisebouyer** [comment]
Oui carrément!
